### ISSUE TITLE
how to build a project?

### ISSUE THREAD

**Issue by lootoos** [lhridder/gamma#1]
how to build a program?
how do I run the program?

**Comment by lhridder** [comment]
Hi,

You can run the program by cloning the repository, cd'ing into cmd/gamma and running `go build .`
Then you can move the binary to wherever you plan on using it and also make a configs directory and a config.yml in that working directory.
The config.yml can be copied from the readme or just an empty yaml file.
In the configs directory you can create a .json file according to the minimal config in the readme.
Then u can start it with `./gamma`

**Comment by lootoos** [comment]
no works:https://ibb.co/CHT8nc6 https://ibb.co/JvTKgYT https://ibb.co/GxYt8sk https://ibb.co/dJj7Kty https://ibb.co/CWXhGy9

**Comment by lhridder** [comment]
It seems like you didn’t put the config.yml in the working directory (the directory the binary is in)

**Comment by lootoos** [comment]
a new problem: https://ibb.co/Sc3Xs91

**Comment by lhridder** [comment]
You are missing a " on line 4 of the .json

**Comment by lootoos** [comment]
here:https://ibb.co/zHZDg51 ?

**Comment by lhridder** [comment]
Yes at the beginning of the value of proxyTo but u seem to have put the json config in a .yml file

**Comment by lootoos** [comment]
is json so necessary?

**Comment by lootoos** [comment]
a new problem: https://ibb.co/hC9GLyr

**Comment by lhridder** [comment]
yes, the file needs to have .json at the end to load and you're using json syntax so naming the file yml only makes it confusing

**Comment by lootoos** [comment]
does not work if .yml to do instead .json

**Comment by lhridder** [comment]
i don't understand what you mean by that

**Comment by lootoos** [comment]
https://ibb.co/ZhzPjv6

**Comment by lhridder** [comment]
You have now removed the global config which is yml, the individual config is .json and must go in the configs directory

**Comment by lootoos** [comment]
my config:https://pastebin.com/PXsLhJeR

**Comment by lootoos** [comment]
> You have now removed the global config which is yml, the individual config is .json and must go in the configs directory

I have already set it up as it should - now it works, but it does not enter the geyser

**Comment by lhridder** [comment]
if you enable debug mode in the global config.yml and restart, are there any errors in the console?

**Comment by lootoos** [comment]
everything seems to be in order
