### ISSUE TITLE
Plugin "geyser"

### ISSUE THREAD

**Issue by lootoos** [lhridder/gamma#2]
is the program not compatible with the geyser plugin?

**Comment by lhridder** [comment]
the program is meant for use with geyser

**Comment by lootoos** [comment]
does your program support version 1.19.20 of the game?

**Comment by lhridder** [comment]
yes

**Comment by lootoos** [comment]
my config https://pastebin.com/PXsLhJeR

**Comment by lhridder** [comment]
please keep this in the first issue
